package gui;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import db.DBConnector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.bson.Document;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class MainFrame extends javax.swing.JFrame {

    private JTable table;
    private DefaultTableModel tableModel;
    private String currentUser;

    public MainFrame(String username) {
        initComponents();
        this.currentUser = username;
        welcomeLabel.setText("Welcome, " + username);
        this.table = bukuTabel;
        this.tableModel = (DefaultTableModel) bukuTabel.getModel();
        loadDataBuku();
        setupListeners();
    }

    private void loadDataBuku() {
        MongoCollection<Document> collection = DBConnector.connect().getCollection("books");
        FindIterable<Document> docs = collection.find();

        tableModel.setRowCount(0);

        for (Document doc : docs) {
            String judul = doc.getString("Judul");
            String penulis = doc.getString("Penulis");
            String tahunString = doc.getString("Tahun");
            int tahun = 0;
            if (tahunString != null && !tahunString.isEmpty()) {
                try {
                    tahun = Integer.parseInt(tahunString);
                } catch (NumberFormatException e) {
                    System.err.println("Warning: Could not parse 'Tahun' as integer: " + tahunString);
                }
            }
            String kategori = doc.getString("Kategori");
            String status = doc.getString("Status");

            tableModel.addRow(new Object[]{judul, penulis, tahun, kategori, status});
        }
    }

    private void setupListeners() {
        table.getSelectionModel().addListSelectionListener(e -> {
            int row = table.getSelectedRow();
            if (row >= 0) {
                String status = (String) tableModel.getValueAt(row, 4);
                pinjamBtn.setEnabled("Tersedia".equalsIgnoreCase(status));
            }
        });
    }

    private MainFrame() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        kelolaButon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bukuTabel = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        cariField = new javax.swing.JTextField();
        cariButton = new javax.swing.JButton();
        pinjamBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        welcomeLabel.setText("Welcome");

        kelolaButon.setText("Bukuku");
        kelolaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelolaButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kelolaButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutBtn)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBtn)
                    .addComponent(welcomeLabel)
                    .addComponent(kelolaButon))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        bukuTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Judul", "Penulis", "Tahun", "Kategori", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bukuTabel);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cariButton.setText("Search");

        pinjamBtn.setText("Borrow");
        pinjamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cariField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinjamBtn)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariButton)
                    .addComponent(pinjamBtn))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void pinjamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamBtnActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if (row == -1) {
            return;
        }

        String judul = (String) tableModel.getValueAt(row, 0);
        String status = (String) tableModel.getValueAt(row, 4);

        if (!"Tersedia".equalsIgnoreCase(status)) {
            JOptionPane.showMessageDialog(this, "Buku tidak tersedia.");
            return;
        }

        var books = DBConnector.connect().getCollection("books");
        var peminjaman = DBConnector.connect().getCollection("peminjaman");

        long jumlahDipinjam = peminjaman.countDocuments(
                new Document("user", currentUser).append("dikembalikan", false)
        );

        if (jumlahDipinjam >= 3) {
            JOptionPane.showMessageDialog(this, "Kamu sudah meminjam 3 buku. Kembalikan dulu sebelum pinjam lagi.");
            return;
        }

        try {
            books.updateOne(
                    new Document("Judul", judul),
                    new Document("$set", new Document("Status", "Dipinjam"))
            );

            Document trx = new Document("judul", judul)
                    .append("user", currentUser)
                    .append("tanggalPinjam", new java.util.Date())
                    .append("dikembalikan", false);

            peminjaman.insertOne(trx);

            JOptionPane.showMessageDialog(this, "Berhasil pinjam buku: " + judul);
            loadDataBuku();
            pinjamBtn.setEnabled(false);
        } catch (com.mongodb.MongoException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memproses peminjaman: " + e.getMessage(), "Error Peminjaman", JOptionPane.ERROR_MESSAGE);
            System.err.println("MongoDB error during borrow: " + e.getMessage());
        }
    }//GEN-LAST:event_pinjamBtnActionPerformed

    private void kelolaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelolaButonActionPerformed
        // TODO add your handling code here:
        dispose();
        new ManageFrame(currentUser).setVisible(true);
    }//GEN-LAST:event_kelolaButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bukuTabel;
    private javax.swing.JButton cariButton;
    private javax.swing.JTextField cariField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kelolaButon;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton pinjamBtn;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
